version: "2"
services:
  app:
    image: golang:1.9.2
    ports:
      - "3030:3030"
    volumes:
      - .:/go/src/github.com/jpoles1/GoToGym
    working_dir: /go/src/github.com/jpoles1/GoToGym
    command: bash -c "go get github.com/golang/dep/cmd/dep && dep ensure && go build . && ./GoToGym"
    #command: bash -c "go build . && ./GoToGym"
    links:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo
    restart: unless-stopped
  mongo:
    image: mongo
    volumes:
      - mdata:/data/db
    restart: unless-stopped
volumes:
  mdata:
